---
# tasks file for set_network
- name: Get distro
  debug: var=ansible_distribution

- name: Include distribution specific tasks to set network
  include_tasks:
    file: "{{ ansible_distribution | lower }}_setup.yml"
